### ISSUE TITLE
site.pages 变量内容在哪设置

### ISSUE THREAD

**Issue by jsuyanyong** [qiubaiying/qiubaiying.github.io#141]
在nav.html中有如下代码
`{% for page in site.pages %}{% if page.title %}`

这里site.pages是在哪里设置的，变量内容有哪些，因为我需要添加一个页面！我看了配置文件里没有，难道是默认？

@qiubaiying

**Comment by qiubaiying** [comment]
参照about.html的头配置 新建一个.html就可以了




| |
邱柏荧
邮箱：qiubaiyingios@163.com
|

签名由 网易邮箱大师 定制

在2018年07月26日 15:41，Yong Yan 写道：

在nav.html中有如下代码
{% for page in site.pages %}{% if page.title %}

这里site.pages是在哪里设置的，变量内容有哪些，因为我需要添加一个页面！我看了配置文件里没有，难道是默认？

@qiubaiying
