### ISSUE TITLE
Gitalk加载不出来，一直提示issue未创建

### ISSUE THREAD

**Issue by 441985745** [qiubaiying/qiubaiying.github.io#143]
你好，我fork了你的项目，然后根据你Gitalk的教程使用了此插件，但是博客里一直显示联系管理员初始化issue，如果有时间，能麻烦你帮我看一下吗，谢谢了

**Comment by NSDingFan** [comment]
可能是项目 Settings 里 Issues 选项没有打开，可以确认一下。
![image](https://user-images.githubusercontent.com/17693258/44774823-aff83400-aba6-11e8-94c7-fbf3876736ad.png)
