### ISSUE TITLE
Disqus无法加载

### ISSUE THREAD

**Issue by QiWang19** [qiubaiying/qiubaiying.github.io#162]
Disqus配置一直踩坑，能再写一下是不是需要universal code，怎么配置吗？我这边不是教程中说的网络问题。

**Comment by NSDingFan** [comment]
参见官网指南： https://disqus.com/admin/install/platforms/jekyll/
另外，也可以看看其他fork此主题的用户是否有在使用disqus评论功能的。
也可以参考这篇blog：http://blog.zxbing0066.com/jekyll/2014/11/12/disqus.html

**Comment by QiWang19** [comment]
谢谢🙏，是short name设置错误

**Comment by vuittonatehsn** [comment]
@QiWang19 請問我也遇到disqus載不出來問題，顯示"We were unable to load Disqus. If you are a moderator please see our troubleshooting guide." 請問您有遇到相同問題嗎?

**Comment by QiWang19** [comment]
@vuittonatehsn 是的，或者点击右上角，add disqus to my site,设置username，也会生成short name👍
