### ISSUE TITLE
在博客首页导航栏上少了“about”页面

### ISSUE THREAD

**Issue by wock1987** [qiubaiying/qiubaiying.github.io#181]
首先感谢作者的模板，从你这复制后，我上传了github，但是发现在博客首页导航栏上少了“about”页面，只有HOME、TAGS页面，请问这个是什么在控制？期待你的解答。

**Comment by wock1987** [comment]
请问这个在哪个文件当中？我好像没改动什么。

**Comment by DJMeng** [comment]
@wock1987 请问您解决了吗？我这边也遇见该问题。还在查找原因。还望您有空告知一下。
