### ISSUE TITLE
域名问题

### ISSUE THREAD

**Issue by shagody** [qiubaiying/qiubaiying.github.io#208]
CNAME设置了域名zjutiec.top，阿里云里域名解析也对www.zjutiec.top操作过，但是为什么我只能访问zjutiec.top不能访问www.zjutiec.top
想问博主是怎么解析的

**Comment by frankopt** [comment]
CNAME设置域名前frankest.github.io可正常访问，设置域名frankshi.top后, frankest.github.io 和 frankshi.top 均不能访问了，
请问具体是哪里出错了？
