### ISSUE TITLE
新手开BLOG的几个问题

### ISSUE THREAD

**Issue by LockeJet** [qiubaiying/qiubaiying.github.io#387]
本人新手，尝试建立自己的博客，有几大问题：
post目录下新增了Test.md等文件，结果首页无显示，删除了文件倒是很快就更新；
不知道怎么修改 FEATURED TAGS。
非程序员，不知道如何修改。
我的网页：
https://github.com/LockeJet/lockejet.github.io
谢谢！

**Comment by Felixchen1024** [comment]
同样遇到不更新。。。不知道如何解决

**Comment by LockeJet** [comment]
忘了说了。名字规范化就可以，如改名字为：2020-01-01-Test.md
