### ISSUE TITLE
文章右侧出现多余滚动条.

### ISSUE THREAD

**Issue by jason--liu** [qiubaiying/qiubaiying.github.io#52]
本地测试和网上测试都会出现多余滚动条.
![selection_001](https://user-images.githubusercontent.com/8001473/34336948-58f40210-e996-11e7-9abd-26c9da21e24b.png)

**Comment by qiubaiying** [comment]
你是用的什么浏览器呢，我用 Chrome 和 Safari 都不会出现这种情况呢。

有或者是你动过源码了。

![滚动条](https://user-images.githubusercontent.com/19592098/34337092-a059051e-e997-11e7-8c67-54f82a517678.png)

**Comment by jason--liu** [comment]
用的chrome，没改过源码，只改过_config.yml文件。@qiubaiying

**Comment by jason--liu** [comment]
已解决,修改css文件的`article`的'overflow-x'为'overflow'.

**Comment by mffan0922** [comment]
> 补充一下：修改hux-blog.min.css和hux-blog.css的`article`的`overflow-x`为`overflow`

为什么我的还是有多余的滚动条？？求解啊
