### ISSUE TITLE
怎样能不跳转到自定义域名上？就用github.io

### ISSUE THREAD

**Issue by lgxkdream** [qiubaiying/qiubaiying.github.io#79]
如题

**Comment by liuyiling** [comment]
删除工程中(也就是xx.github.io的仓库中)名为CNAME的文件。

**Comment by lgxkdream** [comment]
然鹅还是不行 https://lgxkdream.github.io

**Comment by qiubaiying** [comment]
当你Fork了这个仓库，修改了仓库名之后，就能直接访问 `yourname.github.io` 了，不需要再任何设置。

**Comment by lgxkdream** [comment]
刚删完CNAME不好使，过一会儿好了 @liuyiling @qiubaiying
